name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Run tests
        run: cargo test --all --verbose

      - name: Run rust-analyzer
        run: |
          cargo install --locked rust-analyzer || true
          rust-analyzer --version

      - name: Check formatting
        run: cargo fmt --all -- --check
